name=RTC
version=1.0.0
author=Silicon Labs / Tamas Jozsi
maintainer=Arduino <info@arduino.cc>
sentence=Enables Real Time Clock use on Zephyr enabled boards
paragraph=With this library you can use your board's Real Time Clock (RTC) capabilities. The library provides functions to set and get the current time and date.
category=Timing
architectures=zephyr_main,zephyr_contrib
includes=rtc.h
