# This file contains all the *static* files and directories that will be added
# to any core package archive.
#
# NOTE: board-specific entries in the 'firmwares/' and 'variants/' directories
#       are automatically added by package.sh depending on the information in
#       'boards.txt', so they should not be included here.

boards.txt
platform.txt
programmers.txt
LICENSE
README.md
doc/
cores/
libraries/
variants/_llext/
variants/_linked/
